### ISSUE TITLE
when finish train epoch, there is a problem in evaluate function, please help me 

### ISSUE THREAD

**Issue by electronicYH** [huaifeng1993/DFANet#14]
I modified the epoch to 174 ,then 
amax@amax:/data/yh/DFANet$ python main.py 
./log/dfanet20190822T2152
Re-starting from epoch 174
load weights from ./log/dfanet20190822T2152/model_dfanet_0173.pt finished.
train finished
Traceback (most recent call last):
  File "main.py", line 42, in <module>
    trainer.evaluate(val_loader)
  File "/data/yh/DFANet/train.py", line 250, in evaluate
    print(data.size())
AttributeError: 'list' object has no attribute 'size'

**Comment by huaifeng1993** [comment]
the function evaluate() was not complete but you can acomplished it by referencing the fucntion train()

**Comment by Juderer** [comment]
hi, I have another question about the function evaluate().
I trained one epoch, then
./log\dfanet20191217T0148
load weights from ./log\dfanet20191217T0148\model_dfanet_0000.pt finished.
train finished
Traceback (most recent call last):
  File "D:\DeepLearning\DFANet\train.py", line 251, in evaluate
    inputs, labels = data['image'], data['gt_map']
TypeError: list indices must be integers or slices, not str
somebody can help me, plz!
