### ISSUE TITLE
Help! How to solve the problem?

### ISSUE THREAD

**Issue by Hekeshi** [huaifeng1993/DFANet#18]
(base) keshi@keshi-Blade:~/DFANet-master$ python main.py
Traceback (most recent call last):                                                                                                                       
  File "main.py", line 40, in <module>                                                                                                                   
    trainer.load_weights(trainer.find_last())                                                                                                            
  File "/home/keshi/DFANet-master/train.py", line 171, in find_last                                                                                      
    dir_name = os.path.join(self.model_dir, dir_names[-2])                                                                                               
IndexError: list index out of range

**Comment by huaifeng1993** [comment]
The function "trainer.finde_last()" is used to return the  latest model weight's path if you haved trained the model and saved it's weight. However if you have got no any model's weight you should annoate this line.

**Comment by Hekeshi** [comment]
Thank you for your reply. After I annotate this line, these new errors come. How to solve it?

(base) keshi@keshi-Blade:~/DFANet-master$ python main.py                                                                                                 
Epoch 0/1499
Traceback (most recent call last):
  File "main.py", line 41, in <module>
    trainer.train(train_loader, val_loader, criterion, 1500)
  File "/home/keshi/DFANet-master/train.py", line 58, in train
    for i, data in enumerate(dataloaders[phase], 0):
  File "/home/keshi/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 278, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "/home/keshi/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 682, in __init__
    w.start()
  File "/home/keshi/anaconda3/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/home/keshi/anaconda3/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/keshi/anaconda3/lib/python3.7/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/home/keshi/anaconda3/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/home/keshi/anaconda3/lib/python3.7/multiprocessing/popen_fork.py", line 70, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

**Comment by Hekeshi** [comment]
huaifeng1993, could you tell me why these errors happen?

**Comment by huaifeng1993** [comment]
Hello ,according to your log report ,this new issue  occured seemingly due to your system resource exhaustion.    Trying to change the parameter "num_workers" in  DataLoader(dataset=val_dataset,batch_size=10, shuffle=False,num_workers=8) into smaller number  "1",the new issue may be solved.

**Comment by Hekeshi** [comment]
After I change the number to 1, the same errors still exist.


Traceback (most recent call last):
  File "main.py", line 41, in <module>
    trainer.train(train_loader, val_loader, criterion, 1500)
  File "/home/keshi/DFANet-master/train.py", line 58, in train
    for i, data in enumerate(dataloaders[phase], 0):
  File "/home/keshi/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 278, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "/home/keshi/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 682, in __init__
    w.start()
  File "/home/keshi/anaconda3/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/home/keshi/anaconda3/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/keshi/anaconda3/lib/python3.7/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/home/keshi/anaconda3/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/home/keshi/anaconda3/lib/python3.7/multiprocessing/popen_fork.py", line 70, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

**Comment by Hekeshi** [comment]
This is my configuration in main.py. please check it. If you find any problems, please tell me.

from  cityscape  import DatasetTrain ,DatasetVal
import argparse
from torch.utils.data import  DataLoader
from pathlib import Path
import yaml
from train import Trainer
from torch.nn import CrossEntropyLoss
import torch.optim as optim
from torch.optim import lr_scheduler
from model.dfanet import dfanet
from config import Config
from loss import CrossEntropyLoss2d

if __name__=='__main__':

    cfg=Config()
    #create dataset
    train_dataset = DatasetTrain(cityscapes_data_path="/home/keshi/Data/DataSet/Cityscape",
                                cityscapes_meta_path="/home/keshi/Data/DataSet/Cityscape/gtFine/")
    val_dataset = DatasetVal(cityscapes_data_path="/home/keshi/Data/DataSet/Cityscape",
                             cityscapes_meta_path="/home/keshi/Data/DataSet/Cityscape/gtFine")       
    train_loader = DataLoader(dataset=train_dataset,
                                           batch_size=10, shuffle=True,
                                           num_workers=1)
    val_loader = DataLoader(dataset=val_dataset,
                                         batch_size=10, shuffle=False, 
                                         num_workers=1)
    net = dfanet(pretrained=False,num_classes=20)
    #load loss
    criterion = CrossEntropyLoss()
    optimizer = optim.SGD(
    net.parameters(), lr=0.1, momentum=0.9,weight_decay=0.00001)  #select the optimizer

    lr_fc=lambda iteration: (1-iteration/400000)**0.9

    exp_lr_scheduler = lr_scheduler.LambdaLR(optimizer,lr_fc,-1)
    
    trainer = Trainer('training', optimizer,exp_lr_scheduler, net, cfg, './log')
   # trainer.load_weights(trainer.find_last())
    trainer.train(train_loader, val_loader, criterion, 1500)
    trainer.evaluate(val_loader)
    print('Finished Training')

**Comment by huaifeng1993** [comment]
I think that this issue was not casued by the code. It seems that your system has no enough resource to run the project.

**Comment by huaifeng1993** [comment]
How much your computer memory has?

**Comment by Hekeshi** [comment]
[sudo] password for keshi: 
# dmidecode 3.0
Getting SMBIOS data from sysfs.
SMBIOS 3.1.1 present.
# SMBIOS implementations newer than version 3.0 are not
# fully supported by this version of dmidecode.

Handle 0x0023, DMI type 16, 23 bytes
Physical Memory Array
        Location: System Board Or Motherboard
        Use: System Memory
        Error Correction Type: None
        Maximum Capacity: 32 GB
        Error Information Handle: Not Provided
        Number Of Devices: 2

Handle 0x0024, DMI type 17, 40 bytes
Memory Device
        Array Handle: 0x0023
        Error Information Handle: Not Provided
        Total Width: 64 bits
        Data Width: 64 bits
        Size: 8192 MB
        Form Factor: SODIMM                                                                                                                              
        Set: None                                                                                                                                        
        Locator: ChannelA-DIMM0                                                                                                                          
        Bank Locator: BANK 0                                                                                                                             
        Type: DDR4                                                                                                                                       
        Type Detail: Synchronous                                                                                                                         
        Speed: 2667 MHz                                                                                                                                  
        Manufacturer: Samsung                                                                                                                            
        Serial Number: 414E7A6E                                                                                                                          
        Asset Tag: 9876543210                                                                                                                            
        Part Number: M471A1K43CB1-CTD                                                                                                                    
        Rank: 1                                                                                                                                          
        Configured Clock Speed: 2667 MHz                                                                                                                 
        Minimum Voltage: 1.2 V                                                                                                                           
        Maximum Voltage: 1.2 V                                                                                                                           
        Configured Voltage: 1.2 V                                                                                                                        
                                                                                                                                                         
Handle 0x0025, DMI type 17, 40 bytes
Memory Device
        Array Handle: 0x0023
        Error Information Handle: Not Provided
        Total Width: 64 bits
        Data Width: 64 bits
        Size: 8192 MB
        Form Factor: SODIMM
        Set: None
        Locator: ChannelB-DIMM0
        Bank Locator: BANK 2
        Type: DDR4
        Type Detail: Synchronous
        Speed: 2667 MHz
        Manufacturer: Samsung
        Serial Number: 414E8B20
        Asset Tag: 9876543210
        Part Number: M471A1K43CB1-CTD    
        Rank: 1
        Configured Clock Speed: 2667 MHz
        Minimum Voltage: 1.2 V
        Maximum Voltage: 1.2 V
        Configured Voltage: 1.2 V

**Comment by Hekeshi** [comment]
Could you tell me the minimum compute resource or your compute resource. My laptop configuration has been given.

**Comment by Hekeshi** [comment]
![Screenshot from 2019-10-10 17-13-47](https://user-images.githubusercontent.com/26731010/66550923-5ae86900-eb81-11e9-9354-931d44f182b9.png)

This is my GPU configuration. Please check it.

**Comment by Hekeshi** [comment]
After I change the number to 0, other errors occurs.

(base) keshi@keshi-Blade:~/DFANet-master$ python main.py
Epoch 0/1499                                                                                                                                             
Traceback (most recent call last):-----------------]0.34%
  File "main.py", line 41, in <module>
    trainer.train(train_loader, val_loader, criterion, 1500)
  File "/home/keshi/DFANet-master/train.py", line 69, in train
    preds_np=outputs.detach().cpu().numpy()
RuntimeError: [enforce fail at CPUAllocator.cpp:64] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 209715200 bytes. Error code 12 (Cannot allocate memory)

**Comment by huaifeng1993** [comment]
My computer's dfg is: 
memory:16g
Gpus memory:8g

**Comment by huaifeng1993** [comment]
If you have no enough computer's memory,Try to use smaller batchsize.

**Comment by Hekeshi** [comment]
I have used smaller batchsize (1 or 2). However, the same problems still exist.

**Comment by huaifeng1993** [comment]
sorry....I have no idea how to solve this problem..

**Comment by Hekeshi** [comment]
![Screenshot from 2019-10-10 17-54-06](https://user-images.githubusercontent.com/26731010/66553930-fdefb180-eb86-11e9-81a8-447c4bdeac10.png)

**Comment by Hekeshi** [comment]
Do you think it is OK?

**Comment by Hekeshi** [comment]
I just set  batch_size=10, num_workers=0. Now it can work. Could you tell me  whether the settings are suitable or not?

**Comment by huaifeng1993** [comment]
Emmm,this rep is just a rough reImplementation of DFANet and you can see the performance is not good as paper's said. if you want a satisfied performance ,I think you should explore the expeiment by yourself.

**Comment by huaifeng1993** [comment]
I did not write test.py...because the index on  training dataset could not reach the paper's index on testset.

**Comment by Hekeshi** [comment]
Hi  huaifeng1993. Could you tell me whether your code could achieve a fps of 100?  I just care about this fps index.

**Comment by huaifeng1993** [comment]
you can test it by modifing little code in the trainer.detect() function. This links may be helpful to you.  https://github.com/huaifeng1993/Segmentation_of_Cloud_Images/blob/master/detection.py

**Comment by Hekeshi** [comment]
OK. Thank you. I will try it.

**Comment by Hekeshi** [comment]
huaifeng1993 , do you know how to adopt the suitable torchvision version for torch 1.0.0. I sometimes will meet the errors as follows: **ninja: build stopped: subcommand failed.**, **subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.**
