### ISSUE TITLE
How to Solve My Problem?

### ISSUE THREAD

**Issue by CoolLoveBoy** [huaifeng1993/DFANet#26]
When I python3 main.py, it occur the problem:
train finished
Traceback (most recent call last):
  File "main.py", line 42, in <module>
    trainer.evaluate(val_loader)
  File "/home/coollove/SemanticSegmentation/DFANet-master/train.py", line 251, in evaluate
    inputs, labels = data['image'], data['gt_map']
TypeError: list indices must be integers or slices, not str
What can I do to solve this problem!

**Comment by huaifeng1993** [comment]
The function of evaluating has not completed,but you can finished it easily by refereing of training function.

**Comment by CoolLoveBoy** [comment]
Could you provide the function of evaluating? If you have done, I will thanks very much.

**Comment by huaifeng1993** [comment]
This project is being reconstructed and the function will be accomplished.
