### ISSUE TITLE
I am executing  main.py  times error as follows: how to solve?

### ISSUE THREAD

**Issue by liangcheng123** [huaifeng1993/DFANet#30]
Traceback (most recent call last):
  File "E:/DFANet-master/main.py", line 46, in <module>
    trainer.evaluate(val_loader)
  File "E:\DFANet-master\train.py", line 252, in evaluate
    inputs, labels = data['image'], data['gt_map']
TypeError: list indices must be integers or slices, not str

**Comment by huaifeng1993** [comment]
The function eval has not completed but you can finshine it according to the training process.
