### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by SecondLi** [huaifeng1993/DFANet#6]
pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:103: void cunn_SpatialClassNLLCriterion_updateOutput_kernel(T *, T *, T *, long *, T *, int, int, int, int, int, long) [with T = float, AccumT = float]: block: [5,0,0], thread: [799,0,0] Assertion `t >= 0 && t < n_classes` failed.
Traceback (most recent call last):
  File "main.py", line 40, in <module>
    trainer.train(train_loader, val_loader, criterion, 1500)
  File "/media/yazhou/data_drive3/lyj/DFANet/train.py", line 69, in train
    preds_np=outputs.detach().cpu().numpy()
RuntimeError: CUDA error: device-side assert triggered

I am having a problem while training the network.The model starts training but it throws this error

**Comment by huaifeng1993** [comment]
sorry ,I have no idea about what cause the error you meet.

**Comment by Zwei1996** [comment]
criterion = CrossEntropyLoss(ignore_index=255)

**Comment by minastinisofking** [comment]
> criterion = CrossEntropyLoss(ignore_index=255)

Thank you very much!!!
